@startuml

left to right direction

    actor Gerente_de_Compras as gc
    actor Supervisor_de_Estoque as sde
    actor Coordenador_de_Produção as cp
    actor Analista_de_Qualidade as aq 
    actor Gerente_de_Vendas as gv
    actor Vendedor as vd 

    usecase "Organizar Materiais" as om  
    usecase "Gerenciar Materiais" as gm
    usecase "Supervisionar Estoque" as se
    usecase "Receber Comissão" as rc
    usecase "Vender Produtos" as vp
    usecase "Controlar Vendas" as cv
    usecase "Comprar Materiais" as cma
    usecase "Conferir e Verificar Materiais" as cvm
    usecase "Garantir a entrega dos Materiais" as gem
    usecase "Planejar a utilização dos Materiais" as pum
    usecase "Monitorar o Processo de Produção" as mpp
    usecase "Conduzir Inspeções Regulares" as cir
    usecase "Coordenar a entrega dos Produtos" as cep
    usecase "Registrar todas as Vendas" as rtv 
    usecase "Formar equipe de Vendas" as fev
    usecase "Cumprir Cotas" as cc 

    vd -- rc
    vd -- cc 
    vd -- vp 
    gv -- cv 
    gv -- fev 
    (rc) .> (vp) : <<inclui>> 
    sde -- gm 
    gv --|> vd 
    gc -- cma 
    gc --|> sde 
    sde -- cvm 
    cp -- pum 
    aq --mpp
    aq -- cir 
    vd -- cep 
    vd -- rtv 
    sde -- om 
    cp -- gem 
    sde -- se 

@enduml  